development:
  adapter: postgresql
  encoding: unicode
  database: restaurant_reservations_development
  host: localhost
  pool: 5
  username: restaurant_reservations
  password: test

test:
  adapter: postgresql
  encoding: unicode
  database: restaurant_reservations_test
  host: localhost
  pool: 5
  username: restaurant_reservations
  password: test
